### PR TITLE
Php 8.0.0

### PR DESCRIPTION
**Pull request by bhamail**
Trying to get things to build and work with PHP 8.0.0.

Help on this is welcome!

### CODE REVIEW

**Comment by DarthHater** [comment]
@bhamail , https://github.com/laravel/tinker is what is enabled by `tinker-zero`. `bach` is using laravel-zero to build the application, so you probably removed something that the actual framework relies on, lol.

**Comment by bhamail** [comment]
@DarthHater Yep, and `tinker-zero` has require:  ["php": "^7.2.5"](https://github.com/intonate/tinker-zero/blob/master/composer.json#L18), so not sure how to get that to play nice with php 8.

**Comment by DarthHater** [comment]
Screen Shot 2021-02-16 at 9 16 33 AM

DAN SHOOTS DAN SCORES

**Comment by jkowalleck** [comment]
@bhamail this merge might have caused a lot of trouble, since this project had missing/insufficient CI tests.
I think i might have found all the issues and came up with fixes or test mechanics for it.

**Comment by DarthHater** [comment]
@jkowalleck that is awesome (that you sent us PR's, etc...)

**Pull request merged**
